baseURL = "https://teddymartin.co/"
languageCode = "en-us"
title = "Teddy's Homepage"
theme = "ananke"
SectionPagesMenu = "main"

[params]
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  instagram = ""
  youtube = ""
  github = "https://github.com/ejmartin504"
  linkedin = "https://www.linkedin.com/in/teddy-jerome-martin/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-mid-gray"
  featured_image = ""
  recent_posts_number = 2